version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sequelize
    versions:
    - 6.5.0
    - 6.5.1
    - 6.6.1
  - dependency-name: jasmine
    versions:
    - 3.6.4
  - dependency-name: pg
    versions:
    - 8.5.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: inquirer
    versions:
    - 7.3.3
